version: "3"

networks:
  laravel:
    name: laravel

services:
  # PHP 8
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./web/src:/var/www/html
    networks:
      - laravel

  #MySQL Services
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/sql:/sql
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
    networks:
      - laravel
